version: '2.1'
services:
    test-AMQP:
        image: networke2e/node-test
        privileged: true
        env_file: amqp_env.txt
        command: C:\\node-sdk\\network_e2e\\run-badnetwork-e2e.cmd amqp bad_network
        networks:
            - default
        volumes:
            - C:\DockerKeys:C:\users\ContainerAdministrator\.docker

    test-AMQP-WS:
        image: networke2e/node-test
        privileged: true
        env_file: amqp_ws_env.txt
        command: C:\\node-sdk\\network_e2e\\run-badnetwork-e2e.cmd amqp-ws bad_network
        networks:
            - default
        volumes:
            - C:\DockerKeys:C:\users\ContainerAdministrator\.docker

    test-MQTT:
        image: networke2e/node-test
        privileged: true
        env_file: mqtt_env.txt
        command: C:\\node-sdk\\network_e2e\\run-badnetwork-e2e.cmd mqtt bad_network
        networks:
            - default
        volumes:
            - C:\DockerKeys:C:\users\ContainerAdministrator\.docker

    test-MQTT-WS:
        image: networke2e/node-test
        privileged: true
        env_file: mqtt_ws_env.txt
        command: C:\\node-sdk\\network_e2e\\run-badnetwork-e2e.cmd mqtt-ws bad_network
        networks:
            - default
        volumes:
            - C:\DockerKeys:C:\users\ContainerAdministrator\.docker

networks:
    default:
        external:
            name: nat

